In [122]:
import numpy as np

In [123]:
a = [10,20,30,40]

In [124]:
type(a)

list

In [125]:
x = np.array(a)

In [126]:
print(x)

[10 20 30 40]


In [127]:
type(x)

numpy.ndarray

In [128]:
a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

In [129]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [130]:
import numpy as np

a = [1, 2, 3, 4]
b = [10, 20, 30, 40]

x = np.array([a, b])
print(x)


[[ 1  2  3  4]
 [10 20 30 40]]


In [131]:
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [132]:
x = np.array([1,2,3,4], dtype = np.float32)
print(x)

[1. 2. 3. 4.]


In [133]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [134]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [135]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
np.ones(5, dtype = np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [137]:
x = np.random.rand(2,5)

In [138]:
print(x)

[[0.78144755 0.40685735 0.23067173 0.24036729 0.15045217]
 [0.9977473  0.11455921 0.58849264 0.63198461 0.02477203]]


In [139]:
import numpy as np

print(np.random.rand(3, 2))

[[0.00640554 0.04349755]
 [0.53532883 0.73974757]
 [0.99240112 0.98282864]]


In [140]:
np.random.randint(1,20, size = (3,3))

array([[19, 15, 18],
       [17, 15, 11],
       [10, 15,  3]], dtype=int32)

In [141]:
import numpy as np

print(np.random.randint(1, 10, size=(3, 2)))

[[5 6]
 [8 4]
 [4 2]]


In [142]:
np.random.randn(2,5)

array([[ 2.20340248, -0.64624363, -0.31257683, -0.06666696, -2.19474431],
       [ 0.87050927, -0.11088685, -1.55967821, -0.46754963,  1.23279894]])

In [143]:
import numpy as np

x = np.random.randn(3, 2)
print(x)

[[-1.47439326 -0.59724506]
 [-0.21327496 -0.65012702]
 [-0.27596327 -0.3212966 ]]


In [144]:
np.random.choice([2,3,4,7,8,10])

np.int64(7)

In [145]:
np.full((3,4),10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [146]:
np.ones((3,3))*10

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [147]:
x = np.eye(4, k = -1)
print(x)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [148]:
import numpy as np

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [149]:
np.arange(5,11)

array([ 5,  6,  7,  8,  9, 10])

In [150]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [151]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [152]:
a = [10,20,30,40,50]
x = np.array(a)
print(x)

[10 20 30 40 50]


In [153]:
x.ndim

1

In [154]:
b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

[[10 20 30 40 50]
 [ 1  2  3  4  5]]


In [155]:
y.ndim

2

In [156]:
y.shape

(2, 5)

In [157]:
y.size

10

In [158]:
a = np.array([3,6,9,12])
print(a)

[ 3  6  9 12]


In [159]:
np.reshape(a, (2,2))

array([[ 3,  6],
       [ 9, 12]])

In [160]:
a.reshape(2,2)

array([[ 3,  6],
       [ 9, 12]])

In [161]:
x = np.arange(1,16)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [162]:
x.size

15

In [163]:
x.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [164]:
x = np.arange(1,16)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [165]:
y = x.reshape(3,5)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [166]:
z = np.transpose(y)
print(z)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [167]:
y.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [168]:
a = np.arange(1,10)

In [169]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [170]:
a[2:6]

array([3, 4, 5, 6])

In [171]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [172]:
x[1,2]

np.int64(6)

In [173]:
x[1][2]

np.int64(6)

In [174]:
x[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [175]:
a = np.arange(1,6)
b = np.arange(6,11)

In [176]:
print(a)

[1 2 3 4 5]


In [177]:
print(b)

[ 6  7  8  9 10]


In [178]:
x = np.vstack((a,b))

In [179]:
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [180]:
x = np.hstack((a,b))

In [181]:
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [182]:
a = np.arange(1,10).reshape(3,3)

In [183]:
b = np.arange(10,19).reshape(3,3)

In [184]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [185]:
print(b)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [186]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [187]:
np.concatenate((a,b), axis = 1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [188]:
a = np.arange(10,21,2)

In [189]:
b = np.array([[2],[2]])

In [190]:
print(a)

[10 12 14 16 18 20]


In [191]:
print(b)

[[2]
 [2]]


In [192]:
z = a+b
print(z)

[[12 14 16 18 20 22]
 [12 14 16 18 20 22]]


In [193]:
a = np.arange(10,21,2)

In [194]:
a+2

array([12, 14, 16, 18, 20, 22])

In [195]:
a - b

array([[ 8, 10, 12, 14, 16, 18],
       [ 8, 10, 12, 14, 16, 18]])

In [196]:
a*b

array([[20, 24, 28, 32, 36, 40],
       [20, 24, 28, 32, 36, 40]])

In [197]:
a = np.ones((3,3))
b = np.array([2])
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [198]:
print(b)

[2]


In [199]:
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [200]:
a-b

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [201]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [202]:
print(a+5)

[[6. 5. 5. 5.]
 [5. 6. 5. 5.]
 [5. 5. 6. 5.]
 [5. 5. 5. 6.]]


In [203]:
a - 1

array([[ 0., -1., -1., -1.],
       [-1.,  0., -1., -1.],
       [-1., -1.,  0., -1.],
       [-1., -1., -1.,  0.]])

In [204]:
a*2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [205]:
a/0.5

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 2.]])

In [206]:
np.sin(a)

array([[0.84147098, 0.        , 0.        , 0.        ],
       [0.        , 0.84147098, 0.        , 0.        ],
       [0.        , 0.        , 0.84147098, 0.        ],
       [0.        , 0.        , 0.        , 0.84147098]])

In [207]:
np.cos(a)

array([[0.54030231, 1.        , 1.        , 1.        ],
       [1.        , 0.54030231, 1.        , 1.        ],
       [1.        , 1.        , 0.54030231, 1.        ],
       [1.        , 1.        , 1.        , 0.54030231]])

In [208]:
np.sqrt(a)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [209]:
a = np.arange(5,15,2)

In [210]:
print(a)

[ 5  7  9 11 13]


In [211]:
np.mean(a)

np.float64(9.0)

In [212]:
np.median(a)

np.float64(9.0)

In [213]:
np.std(a)

np.float64(2.8284271247461903)

In [214]:
a = np.array([[1,6],[4,3]])
print(a)

[[1 6]
 [4 3]]


In [215]:
print(np.min(a, axis = 0))

[1 3]


In [216]:
print(np.min(a, axis = 1))

[1 3]


In [217]:
print(np.max(a, axis = 1))

[6 4]


In [218]:
print(np.max(a, axis = 0))

[4 6]


In [219]:
a = np.array([1,4,3,10,20])

In [220]:
x = np.sort(a, kind = 'mergesort')

In [221]:
print(x)

[ 1  3  4 10 20]


In [222]:
A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))

In [223]:
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [224]:
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [225]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [226]:
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])